### ISSUE TITLE
train_stable_baseline.py 執行會卡在無限迴圈

### ISSUE THREAD

**Issue by a240888** [Bacon9629/PyAutoDriveRL-Env#2]
![image](https://github.com/user-attachments/assets/634917c5-4d1c-425e-8e25-37a23685242d)
步驟順序:開啟unity應用程式->執行python train_stable_baseline.py->unity重製車子位置
command line:
(34256) wsgi starting up on http://0.0.0.0:4567
(34256) accepted ('127.0.0.1', 9224)
Client connected: f05a45d5d1b74732889b25e6c979bc42
之後就會卡在151、152行無限循環

**Comment by Bacon9629** [comment]
嗨同學
感謝你的回報，bug已經修正，bug發生原因為昨日更新的功能沒有在其他script上同步更新所導致
請再次git pull取得最新程式碼
